name = "The Botanist's Journey"
author = "Botany"
version = "0.0.79"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e61355599f9a6fbcc444170fa62f3d302392f54ed79ec8f36b90067e326b7c55"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
