name = "The Botanist's Journey"
author = "Botany"
version = "0.0.79"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64128218cb791c4558a63555c0e8b6039ef8f8509207c6fd4d47a73107768d99"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
