name = "The Botanist's Journey"
author = "Botany"
version = "0.0.79"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f52989d75217ad5911de04e4da943b4c1a67f22a3a1d682b3d7a22827b829da0"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
