name = "The Botanist's Journey"
author = "Botany"
version = "0.0.79"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b02d880a9341507f91b78f3b58001761fdf7a9961cb79f6d29c8f4a793f5e1c1"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
