name = "The Botanist's Journey"
author = "Botany"
version = "0.0.79"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccebc53ed5fad20281f515fa8139475e42d7d4c5054976e4b0ae24ba33cdc778"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
