# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				squid = true
				chest_minecart = true
				wolf = true
				bat = true
				glow_squid = true
				zombie = true
				creeper = true
				skeleton = true
				cod = true
				enderman = true
				axolotl = true
				spider = true
				salmon = true
				item = true
				witch = true
				bee = true
				zombie_villager = true
				vindicator = true
				pillager = true
				rabbit = true
				item_frame = true
				villager = true
				husk = true
				armor_stand = true
				slime = true
				tropical_fish = true
				iron_golem = true
				cat = true
				cave_spider = true
				experience_orb = true
				sheep = true
				cow = true
				pig = true
				chicken = true
				horse = true
				allay = true
				painting = true
				drowned = true
				arrow = true
				pufferfish = true
				panda = true
				tnt_minecart = true
				parrot = true
				ocelot = true
				turtle = true
				fox = true
				dolphin = true
				donkey = true
				strider = true
				zombified_piglin = true
				piglin = true
				magma_cube = true
				blaze = true
				ghast = true
				illusioner = true
				vex = true
				evoker = true
				wither_skeleton = true
				ravager = true
				phantom = true
				piglin_brute = true
				hoglin = true
				ender_dragon = true
				endermite = true
				potion = true

			[light_sources.settings.entities.earthtojavamobs]
				wooly_cow = true
				pink_footed_pig = true
				pinto_cow = true
				midnight_chicken = true
				fuzzy_sheep = true
				bold_striped_rabbit = true
				flecked_sheep = true
				skeleton_wolf = true
				muddy_pig = true
				cream_cow = true
				rainbow_sheep = true
				piebald_pig = true
				freckled_rabbit = true
				fancy_chicken = true
				skewbald_chicken = true
				gold_crested_chicken = true
				stormy_chicken = true
				pale_pig = true
				jolly_llama = true
				cookie_cow = true
				amber_chicken = true
				sooty_pig = true
				long_nosed_sheep = true
				sunset_cow = true

			[light_sources.settings.entities.betteranimalsplus]
				badger = true
				goose = true
				shark = true
				whale = true
				jellyfish = true
				turkey = true
				butterfly = true
				eel_freshwater = true
				lamprey = true
				coyote = true
				tarantula = true
				songbird = true
				boar = true
				badgerdirt = true
				blackbear = true
				crab = true
				horseshoecrab = true
				pheasant = true
				eel_saltwater = true
				nautilus = true
				flying_fish = true
				barracuda = true
				octopus = true
				piranha = true
				brownbear = true
				feralwolf = true
				deer = true
				bobbit_worm = true

			[light_sources.settings.entities.mimic]
				mimic = true

			[light_sources.settings.entities.adventurez]
				deer = true
				amethyst_golem = true
				iguana = true
				orc = true
				nightmare = true
				soul_reaper = true
				enderwarthog = true
				ender_whale = true

			[light_sources.settings.entities.graveyard]
				revenant = true
				skeleton_creeper = true
				ghoul = true
				nightmare = true
				acolyte = true
				corrupted_vindicator = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				dripstone_creeper = true
				desert_creeper = true
				badlands_creeper = true
				dark_oak_creeper = true
				bamboo_creeper = true
				snowy_creeper = true
				savannah_creeper = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				mauler = true
				copper_golem = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.tumbleweed]
				tumbleweed = true

			[light_sources.settings.entities.creatures_of_the_snow]
				reindeer = true
				leopard = true

			[light_sources.settings.entities.aqupd]
				caracal = true

			[light_sources.settings.entities.betternether]
				skull = true
				hydrogen_jellyfish = true
				firefly = true
				naga = true

			[light_sources.settings.entities.edenring]
				diskwing = true
				lightning_ray = true

			[light_sources.settings.entities.betterend]
				end_slime = true
				shadow_walker = true
				silk_moth = true

			[light_sources.settings.entities.twigs]
				pebble = true

